// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppCard: typeof import('./components/AppCard.vue')['default']
    AppInputSearch: typeof import('./components/AppInputSearch.vue')['default']
    AppRegionSelect: typeof import('./components/AppRegionSelect.vue')['default']
    AppSelect: typeof import('./components/AppSelect.vue')['default']
    TheNavbar: typeof import('./components/TheNavbar.vue')['default']
  }
}

export { }
